/* eslint-disable jsx-a11y/img-redundant-alt */
import "../static/css/categories.css"
import 'bootstrap/dist/css/bootstrap.min.css';
import { Link } from "react-router-dom";
import veg from "../static/img/categories/veg.png";
import nonveg from "../static/img/categories/non-veg.png";
import { Button } from 'reactstrap';
import React, { useEffect, useState } from "react";


const styleCards = {
    padding: "0% 1.5%"

}
const styleInfo = {
    padding: " 6% 0% 6% 5%",


}
const styleImage = {
    display: "flex",
    // eslint-disable-next-line no-undef
    justifyContent: "center",
    alignItems: "center",
    with: "80px",
    padding: "4% 1%",
    height: "250px",
}
const All = () => {
    return (
        <div>

            <div className="cards">
                <div className="row">
                    <div className="col-lg-6  col-sm-12 col-md-8" style={styleCards}>
                        <div className="cont mx-auto">
                            <div className="row">
                                <div className="col-lg-5 col-sm-12" style={styleImage}>
                                    <img src={"https://www.bing.com/th?id=OIP.ugjuF_qKjv8_8R8mp9w1VAFZC0&w=200&h=105&c=8&rs=1&qlt=90&o=6&dpr=1.56&pid=3.1&rm=2"} alt="image" className="dishImage" />
                                </div>
                                <div className="col-lg-7 col-sm-12 ps-lg-0 ps-sm-5 pe-4 " style={styleInfo}>
                                    <span className="nameAndPrice">
                                        <h4> Dish Name</h4>
                                        <span className="price">$15.65</span>
                                    </span><hr />
                                    <p className="p">Some random text generated by me..basically to test it out...Some random text generated by me..basically to test</p>
                                    <div className="veg_nonveg mt-auto">
                                        <Button className="btn  btn-success btns ">Order !</Button><br />
                                        <img src={veg} alt="Veg" width="30px" height="40px" />
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div className="col-lg-6  col-sm-12 col-md-8" style={styleCards}>
                        <div className="cont mx-auto">
                            <div className="row">
                                <div className="col-lg-5 col-sm-12" style={styleImage}>
                                    <img src={"https://www.bing.com/th?id=OIP.ugjuF_qKjv8_8R8mp9w1VAFZC0&w=200&h=105&c=8&rs=1&qlt=90&o=6&dpr=1.56&pid=3.1&rm=2"} alt="image" className="dishImage" />
                                </div>
                                <div className="col-lg-7 col-sm-12 ps-lg-0 ps-sm-4 pe-4" style={styleInfo}>
                                    <span className="nameAndPrice">
                                        <h4>Dish Name</h4>
                                        <span className="price">$15.65</span>
                                    </span><hr />
                                    <p className="p">Some random text generated by me..basically to test it out...Some random text generated by me..basically to test</p>

                                    <div className="veg_nonveg mt-auto">
                                        <Button className="btn  btn-success btns">Order !</Button><br />
                                        <img src={veg} alt="Veg" width="30px" height="40px" />
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div className="col-lg-6  col-sm-12 col-md-8" style={styleCards}>
                        <div className="cont mx-auto">
                            <div className="row">
                                <div className="col-lg-5 col-sm-12" style={styleImage}>
                                    <img src={"https://www.bing.com/th?id=OIP.ugjuF_qKjv8_8R8mp9w1VAFZC0&w=200&h=105&c=8&rs=1&qlt=90&o=6&dpr=1.56&pid=3.1&rm=2"} alt="image" className="dishImage" />
                                </div>
                                <div className="col-lg-7 col-sm-12 ps-lg-0 ps-sm-4 pe-4" style={styleInfo}>
                                    <span className="nameAndPrice">
                                        <h4>Dish Name</h4>
                                        <span className="price">$15.65</span>
                                    </span><hr />
                                    <p className="p">Some random text generated by me..basically to test it out...Some random text generated by me..basically to test</p>

                                    <div className="veg_nonveg mt-auto">
                                        <Button className="btn  btn-success btns">Order !</Button><br />
                                        <img src={veg} alt="Veg" width="30px" height="40px" />
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div className="col-lg-6  col-sm-12 col-md-8" style={styleCards}>
                        <div className="cont mx-auto">
                            <div className="row">
                                <div className="col-lg-5 col-sm-12" style={styleImage}>
                                    <img src={"https://www.bing.com/th?id=OIP.ugjuF_qKjv8_8R8mp9w1VAFZC0&w=200&h=105&c=8&rs=1&qlt=90&o=6&dpr=1.56&pid=3.1&rm=2"} alt="image" className="dishImage" />
                                </div>
                                <div className="col-lg-7 col-sm-12 ps-lg-0 ps-sm-4 pe-4" style={styleInfo}>
                                    <span className="nameAndPrice">
                                        <h4>Dish Name</h4>
                                        <span className="price">$15.65</span>
                                    </span><hr />
                                    <p className="p">Some random text generated by me..basically to test it out...Some random text generated by me..basically to test</p>

                                    <div className="veg_nonveg mt-auto">
                                        <Button className="btn  btn-success btns">Order !</Button><br />
                                        <img src={nonveg} alt="Veg" width="30px" height="40px" />
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    );
}
const Dairy = () => {
    return (
        <div>

            <div className="cards">
                <div className="row">
                    <div className="col-lg-6  col-sm-12 col-md-8" style={styleCards}>
                        <div className="cont mx-auto">
                            <div className="row">
                                <div className="col-lg-5 col-sm-12" style={styleImage}>
                                    <img src={"https://wallpapercave.com/wp/wp3079202.jpg"} alt="image" className="dishImage" />
                                </div>
                                <div className="col-lg-7 col-sm-12 ps-lg-0 ps-sm-4 pe-4" style={styleInfo}>
                                    <span className="nameAndPrice">
                                        <h4>Dish Name</h4>
                                        <span className="price">$15.65</span>
                                    </span><hr />
                                    <p className="p">Some random text generated by me..basically to test it out...Some random text generated by me..basically to test</p>

                                    <div className="veg_nonveg mt-auto">
                                        <Button className="btn  btn-success btns">Order !</Button><br />
                                        <img src={veg} alt="Veg" width="30px" height="40px" />
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div className="col-lg-6  col-sm-12 col-md-8" style={styleCards}>
                        <div className="cont mx-auto">
                            <div className="row">
                                <div className="col-lg-5 col-sm-12" style={styleImage}>
                                    <img src={"https://wallpapercave.com/wp/wp3079202.jpg"} alt="image" className="dishImage" />
                                </div>
                                <div className="col-lg-7 col-sm-12 ps-lg-0 ps-sm-4 pe-4" style={styleInfo}>
                                    <span className="nameAndPrice">
                                        <h4>Dish Name</h4>
                                        <span className="price">$15.65</span>
                                    </span><hr />
                                    <p className="p">Some random text generated by me..basically to test it out...Some random text generated by me..basically to test</p>

                                    <div className="veg_nonveg mt-auto">
                                        <Button className="btn  btn-success btns">Order !</Button><br />
                                        <img src={veg} alt="Veg" width="30px" height="40px" />
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div className="col-lg-6  col-sm-12 col-md-8" style={styleCards}>
                        <div className="cont mx-auto">
                            <div className="row">
                                <div className="col-lg-5 col-sm-12" style={styleImage}>
                                    <img src={"https://wallpapercave.com/wp/wp3079202.jpg"} alt="image" className="dishImage" />
                                </div>
                                <div className="col-lg-7 col-sm-12 ps-lg-0 ps-sm-4 pe-4" style={styleInfo}>
                                    <span className="nameAndPrice">
                                        <h4>Dish Name</h4>
                                        <span className="price">$15.65</span>
                                    </span><hr />
                                    <p className="p">Some random text generated by me..basically to test it out...Some random text generated by me..basically to test</p>

                                    <div className="veg_nonveg mt-auto">
                                        <Button className="btn  btn-success btns">Order !</Button><br />
                                        <img src={veg} alt="Veg" width="30px" height="40px" />
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div className="col-lg-6  col-sm-12 col-md-8" style={styleCards}>
                        <div className="cont mx-auto">
                            <div className="row">
                                <div className="col-lg-5 col-sm-12" style={styleImage}>
                                    <img src={"https://wallpapercave.com/wp/wp3079202.jpg"} alt="image" className="dishImage" />
                                </div>
                                <div className="col-lg-7 col-sm-12 ps-lg-0 ps-sm-4 pe-4" style={styleInfo}>
                                    <span className="nameAndPrice">
                                        <h4>Dish Name</h4>
                                        <span className="price">$15.65</span>
                                    </span><hr />
                                    <p className="p">Some random text generated by me..basically to test it out...Some random text generated by me..basically to test</p>

                                    <div className="veg_nonveg mt-auto">
                                        <Button className="btn  btn-success btns">Order !</Button><br />
                                        <img src={veg} alt="Veg" width="30px" height="40px" />
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    );
}
const Seafood = () => {
    return (
        <div>

            <div className="cards">
                <div className="row">
                    <div className="col-lg-6  col-sm-12 col-md-8" style={styleCards}>
                        <div className="cont mx-auto">
                            <div className="row">
                                <div className="col-lg-5 col-sm-12" style={styleImage}>
                                    <img src={"https://th.bing.com/th/id/OIP.zduCLBbbodHFGgq8-tGcAwHaE8?pid=ImgDet&rs=1"} alt="image" className="dishImage" />
                                </div>
                                <div className="col-lg-7 col-sm-12 ps-lg-0 ps-sm-4 pe-4" style={styleInfo}>
                                    <span className="nameAndPrice">
                                        <h4>Dish Name</h4>
                                        <span className="price">$15.65</span>
                                    </span><hr />
                                    <p className="p">Some random text generated by me..basically to test it out...Some random text generated by me..basically to test</p>

                                    <div className="veg_nonveg mt-auto">
                                        <Button className="btn  btn-success btns">Order !</Button><br />
                                        <img src={veg} alt="Veg" width="30px" height="40px" />
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div className="col-lg-6  col-sm-12 col-md-8" style={styleCards}>
                        <div className="cont mx-auto">
                            <div className="row">
                                <div className="col-lg-5 col-sm-12" style={styleImage}>
                                    <img src={"https://th.bing.com/th/id/OIP.zduCLBbbodHFGgq8-tGcAwHaE8?pid=ImgDet&rs=1"} alt="image" className="dishImage" />
                                </div>
                                <div className="col-lg-7 col-sm-12 ps-lg-0 ps-sm-4 pe-4" style={styleInfo}>
                                    <span className="nameAndPrice">
                                        <h4>Dish Name</h4>
                                        <span className="price">$15.65</span>
                                    </span><hr />
                                    <p className="p">Some random text generated by me..basically to test it out...Some random text generated by me..basically to test</p>

                                    <div className="veg_nonveg mt-auto">
                                        <Button className="btn  btn-success btns">Order !</Button><br />
                                        <img src={veg} alt="Veg" width="30px" height="40px" />
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div className="col-lg-6  col-sm-12 col-md-8" style={styleCards}>
                        <div className="cont mx-auto">
                            <div className="row">
                                <div className="col-lg-5 col-sm-12" style={styleImage}>
                                    <img src={"https://th.bing.com/th/id/OIP.zduCLBbbodHFGgq8-tGcAwHaE8?pid=ImgDet&rs=1"} alt="image" className="dishImage" />
                                </div>
                                <div className="col-lg-7 col-sm-12 ps-lg-0 ps-sm-4 pe-4" style={styleInfo}>
                                    <span className="nameAndPrice">
                                        <h4>Dish Name</h4>
                                        <span className="price">$15.65</span>
                                    </span><hr />
                                    <p className="p">Some random text generated by me..basically to test it out...Some random text generated by me..basically to test</p>

                                    <div className="veg_nonveg mt-auto">
                                        <Button className="btn  btn-success btns">Order !</Button><br />
                                        <img src={veg} alt="Veg" width="30px" height="40px" />
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div className="col-lg-6  col-sm-12 col-md-8" style={styleCards}>
                        <div className="cont mx-auto">
                            <div className="row">
                                <div className="col-lg-5 col-sm-12" style={styleImage}>
                                    <img src={"https://th.bing.com/th/id/OIP.zduCLBbbodHFGgq8-tGcAwHaE8?pid=ImgDet&rs=1"} alt="image" className="dishImage" />
                                </div>
                                <div className="col-lg-7 col-sm-12 ps-lg-0 ps-sm-4 pe-4" style={styleInfo}>
                                    <span className="nameAndPrice">
                                        <h4>Dish Name</h4>
                                        <span className="price">$15.65</span>
                                    </span><hr />
                                    <p className="p">Some random text generated by me..basically to test it out...Some random text generated by me..basically to test</p>

                                    <div className="veg_nonveg mt-auto">
                                        <Button className="btn  btn-success btns">Order !</Button><br />
                                        <img src={veg} alt="Veg" width="30px" height="40px" />
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    );
}
const Poultry = () => {
    return (
        <div>

            <div className="cards">
                <div className="row">
                    <div className="col-lg-6  col-sm-12 col-md-8" style={styleCards}>
                        <div className="cont mx-auto">
                            <div className="row">
                                <div className="col-lg-5 col-sm-12" style={styleImage}>
                                    <img src={"https://th.bing.com/th/id/OIP.DR6OTKHmADmYRixRpH-MgwHaFj?pid=ImgDet&rs=1"} alt="image" className="dishImage" />
                                </div>
                                <div className="col-lg-7 col-sm-12 ps-lg-0 ps-sm-4 pe-4" style={styleInfo}>
                                    <span className="nameAndPrice">
                                        <h4>Dish Name</h4>
                                        <span className="price">$15.65</span>
                                    </span><hr />
                                    <p className="p">Some random text generated by me..basically to test it out...Some random text generated by me..basically to test</p>

                                    <div className="veg_nonveg mt-auto">
                                        <Button className="btn  btn-success btns">Order !</Button><br />
                                        <img src={veg} alt="Veg" width="30px" height="40px" />
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div className="col-lg-6  col-sm-12 col-md-8" style={styleCards}>
                        <div className="cont mx-auto">
                            <div className="row">
                                <div className="col-lg-5 col-sm-12" style={styleImage}>
                                    <img src={"https://th.bing.com/th/id/OIP.DR6OTKHmADmYRixRpH-MgwHaFj?pid=ImgDet&rs=1"} alt="image" className="dishImage" />
                                </div>
                                <div className="col-lg-7 col-sm-12 ps-lg-0 ps-sm-4 pe-4" style={styleInfo}>
                                    <span className="nameAndPrice">
                                        <h4>Dish Name</h4>
                                        <span className="price">$15.65</span>
                                    </span><hr />
                                    <p className="p">Some random text generated by me..basically to test it out...Some random text generated by me..basically to test</p>

                                    <div className="veg_nonveg mt-auto">
                                        <Button className="btn  btn-success btns">Order !</Button><br />
                                        <img src={veg} alt="Veg" width="30px" height="40px" />
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div className="col-lg-6  col-sm-12 col-md-8" style={styleCards}>
                        <div className="cont mx-auto">
                            <div className="row">
                                <div className="col-lg-5 col-sm-12" style={styleImage}>
                                    <img src={"https://th.bing.com/th/id/OIP.DR6OTKHmADmYRixRpH-MgwHaFj?pid=ImgDet&rs=1"} alt="image" className="dishImage" />
                                </div>
                                <div className="col-lg-7 col-sm-12 ps-lg-0 ps-sm-4 pe-4" style={styleInfo}>
                                    <span className="nameAndPrice">
                                        <h4>Dish Name</h4>
                                        <span className="price">$15.65</span>
                                    </span><hr />
                                    <p className="p">Some random text generated by me..basically to test it out...Some random text generated by me..basically to test</p>

                                    <div className="veg_nonveg mt-auto">
                                        <Button className="btn  btn-success btns">Order !</Button><br />
                                        <img src={veg} alt="Veg" width="30px" height="40px" />
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div className="col-lg-6  col-sm-12 col-md-8" style={styleCards}>
                        <div className="cont mx-auto">
                            <div className="row">
                                <div className="col-lg-5 col-sm-12" style={styleImage}>
                                    <img src={"https://th.bing.com/th/id/OIP.DR6OTKHmADmYRixRpH-MgwHaFj?pid=ImgDet&rs=1"} alt="image" className="dishImage" />
                                </div>
                                <div className="col-lg-7 col-sm-12 ps-lg-0 ps-sm-4 pe-4" style={styleInfo}>
                                    <span className="nameAndPrice">
                                        <h4>Dish Name</h4>
                                        <span className="price">$15.65</span>
                                    </span><hr />
                                    <p className="p">Some random text generated by me..basically to test it out...Some random text generated by me..basically to test</p>

                                    <div className="veg_nonveg mt-auto">
                                        <Button className="btn  btn-success btns">Order !</Button><br />
                                        <img src={veg} alt="Veg" width="30px" height="40px" />
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    );
}
const Grains = () => {
    return (
        <div>

            <div className="cards">
                <div className="row">
                    <div className="col-lg-6  col-sm-12 col-md-8" style={styleCards}>
                        <div className="cont mx-auto">
                            <div className="row">
                                <div className="col-lg-5 col-sm-12" style={styleImage}>
                                    <img src={"https://www.drweil.com/wp-content/uploads/2016/11/diet-nutrition_cooking-cookware_cooking-with-grains-barley_1440x1080_000057355792.jpg"} alt="image" width="90%" height="100%" className="dishImage" />
                                </div>
                                <div className="col-lg-7 col-sm-12 ps-lg-0 ps-sm-4 pe-4" style={styleInfo}>
                                    <span className="nameAndPrice">
                                        <h4>Dish Name</h4>
                                        <span className="price">$15.65</span>
                                    </span><hr />
                                    <p className="p">Some random text generated by me..basically to test it out...Some random text generated by me..basically to test</p>

                                    <div className="veg_nonveg mt-auto">
                                        <Button className="btn  btn-success btns">Order !</Button><br />
                                        <img src={veg} alt="Veg" width="30px" height="40px" />
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div className="col-lg-6  col-sm-12 col-md-8" style={styleCards}>
                        <div className="cont mx-auto">
                            <div className="row">
                                <div className="col-lg-5 col-sm-12" style={styleImage}>
                                    <img src={"https://www.drweil.com/wp-content/uploads/2016/11/diet-nutrition_cooking-cookware_cooking-with-grains-barley_1440x1080_000057355792.jpg"} alt="image" className="dishImage" />
                                </div>
                                <div className="col-lg-7 col-sm-12 ps-lg-0 ps-sm-4 pe-4" style={styleInfo}>
                                    <span className="nameAndPrice">
                                        <h4>Dish Name</h4>
                                        <span className="price">$15.65</span>
                                    </span><hr />
                                    <p className="p">Some random text generated by me..basically to test it out...Some random text generated by me..basically to test</p>

                                    <div className="veg_nonveg mt-auto">
                                        <Button className="btn  btn-success btns">Order !</Button><br />
                                        <img src={veg} alt="Veg" width="30px" height="40px" />
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div className="col-lg-6  col-sm-12 col-md-8" style={styleCards}>
                        <div className="cont mx-auto">
                            <div className="row">
                                <div className="col-lg-5 col-sm-12" style={styleImage}>
                                    <img src={"https://www.drweil.com/wp-content/uploads/2016/11/diet-nutrition_cooking-cookware_cooking-with-grains-barley_1440x1080_000057355792.jpg"} alt="image" className="dishImage" />
                                </div>
                                <div className="col-lg-7 col-sm-12 ps-lg-0 ps-sm-4 pe-4" style={styleInfo}>
                                    <span className="nameAndPrice">
                                        <h4>Dish Name</h4>
                                        <span className="price">$15.65</span>
                                    </span><hr />
                                    <p className="p">Some random text generated by me..basically to test it out...Some random text generated by me..basically to test</p>

                                    <div className="veg_nonveg mt-auto">
                                        <Button className="btn  btn-success btns">Order !</Button><br />
                                        <img src={veg} alt="Veg" width="30px" height="40px" />
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div className="col-lg-6  col-sm-12 col-md-8" style={styleCards}>
                        <div className="cont mx-auto">
                            <div className="row">
                                <div className="col-lg-5 col-sm-12" style={styleImage}>
                                    <img src={"https://www.drweil.com/wp-content/uploads/2016/11/diet-nutrition_cooking-cookware_cooking-with-grains-barley_1440x1080_000057355792.jpg"} alt="image" className="dishImage" />
                                </div>
                                <div className="col-lg-7 col-sm-12 ps-lg-0 ps-sm-4 pe-4" style={styleInfo}>
                                    <span className="nameAndPrice">
                                        <h4>Dish Name</h4>
                                        <span className="price">$15.65</span>
                                    </span><hr />
                                    <p className="p">Some random text generated by me..basically to test it out...Some random text generated by me..basically to test</p>

                                    <div className="veg_nonveg mt-auto">
                                        <Button className="btn  btn-success btns">Order !</Button><br />
                                        <img src={veg} alt="Veg" width="30px" height="40px" />
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    );
}

const BodyCategory = () => {

    const [currentCategory, setCurrentCategory] = useState(<All />);

    return (
        <div>
            <div>
                <div className="row pt-3 px-3 navbar navbar-light bg-light ">
                    <div className="col-lg-2 col-sm-4 ps-lg-5 ps-sm-5 mb-3">

                        <Link className="homeback" to="/" ><img src={"https://graphicsfamily.com/wp-content/uploads/2020/10/Restaurant-logo-design-free-template-scaled.jpg"} alt="logo" height="45px" width="40px" style={{ borderRadius: "100%" }} /></Link>
                        <span className="menu">Menu</span>
                    </div>

                    <div className="col-lg-4 col-sm-8 pe-lg-5">
                        <form class="d-flex">
                            <button class="btn btn-outline-success" type="submit">Search</button>
                            <input class="form-control me-2" type="search" placeholder="eg: Marinefish.." aria-label="Search" />
                        </form>
                    </div>
                </div>
            </div>
            <nav class="navbar navbar-expand-lg navbar-light bg-light">
                <div class="container-fluid">
                    <button class="navbar-toggler ms-2" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon "></span>
                    </button>
                    <div class="collapse navbar-collapse pt-n1" id="navbarNav">
                        <ul class="menulist navbar-nav">
                            <li className="nav-item li ms-n3 first " onClick={() => { setCurrentCategory(<All />) }}>All</li>
                            <li className="nav-item li ms-3" onClick={() => { setCurrentCategory(<Dairy />) }}>Diary</li>
                            <li className="nav-item li ms-3" onClick={() => { setCurrentCategory(<Seafood />) }}>Seafood</li>
                            <li className="nav-item li ms-3" onClick={() => { setCurrentCategory(<Poultry />) }}>Poultry</li>
                            <li className="nav-item li ms-3" onClick={() => { setCurrentCategory(<Grains />) }}>Grains</li>

                        </ul>
                    </div>
                </div>
            </nav>
            {currentCategory}
        </div>
    );
}
export default BodyCategory;